apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260527-004823-l3bnui8drfbe-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260527-004823-l3bnui8drfbe.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260527-004823-l3bnui8drfbe-service
            port:
              number: 80
