apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260527-004823-l3bnui8drfbe-service
spec:
  selector:
    app: enterprise-system-20260527-004823-l3bnui8drfbe
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
